DEFAULT_FONT = "Verdana"
FONT_SIZE_H1 = 20
FONT_SIZE_H2 = 16
FONT_SIZE_NORMAL = 12

DEFAULT_PAD_X = 10
DEFAULT_PAD_Y = 10

POSTER_CANVAS_WIDTH = 230
POSTER_CANVAS_HEIGHT = 345

DEFAULT_POSTER_DIR_PATH = ""
DEFAULT_DATASET_DIR_PATH = ""
DEFAULT_GANN_DIR_PATH = ""

K_MEANS_CLUSTER_TOTAL_TEXT_WIDTH = 2
K_MEANS_CLUSTER_TOTAL_TEXT_FORMAT = "{:.0f}"
K_MEANS_CLUSTER_TOTAL_DEFAULT = 8
K_MEANS_CLUSTER_TOTAL_MIN = 5
K_MEANS_CLUSTER_TOTAL_MAX = 16
K_MEANS_CLUSTER_TOTAL_STEP = 1

TRAINING_RATIO_TEXT_WIDTH = 5
TRAINING_RATIO_TEXT_FORMAT = "{:.2f}"
TRAINING_RATIO_DEFAULT = 0.8
TRAINING_RATIO_MIN = 0.01
TRAINING_RATIO_MAX = 0.99
TRAINING_RATIO_STEP = 0.01

TOTAL_POPULATION_TEXT_WIDTH = 5
TOTAL_POPULATION_TEXT_FORMAT = "{:.0f}"
TOTAL_POPULATION_DEFAULT = 1000
TOTAL_POPULATION_MIN = 100
TOTAL_POPULATION_MAX = 5000
TOTAL_POPULATION_STEP = 10

MUTATION_RATE_TEXT_WIDTH = 7
MUTATION_RATE_TEXT_FORMAT = "{:.5f}"
MUTATION_RATE_DEFAULT = 0.01
MUTATION_RATE_MIN = 0.00001
MUTATION_RATE_MAX = 0.01
MUTATION_RATE_STEP = 0.00001

IMAGE_FILE_TYPES = (
    ('Image files', '*.png *.jpg *.jpeg *.bmp *.tiff *.webm *.gif'),
    ('All files', '*.*')
)
DATASET_FILE_TYPES = (
    ('CSV files', '*.csv'),
    ('All files', '*.*')
)
GANN_FILE_TYPES = (
    ('GANN files', '*.gann'),
    ('All files', '*.*')
)

ABOUT_TITLE = "Biodata Pengembang"
ABOUT_DESCRIPTION = """
Nama \t \t : Jason Alexander
NIM \t \t : 32180082
Kelas \t \t : 7PTI1
Dosen Pembimbing \t : Teady Matius Surya Mulyana, S.Kom., M.Kom.
"""