DEFAULT_FONT = "Verdana"
FONT_SIZE_H0 = 28
FONT_SIZE_H1 = 20
FONT_SIZE_H2 = 16
FONT_SIZE_NORMAL = 12

DEFAULT_PAD_X = 10
DEFAULT_PAD_Y = 10

POSTER_CANVAS_WIDTH = 230
POSTER_CANVAS_HEIGHT = 345

HISTOGRAM_CANVAS_WIDTH = 400
HISTOGRAM_CANVAS_HEIGHT = 350

DEFAULT_POSTER_DIR_PATH = ""
DEFAULT_DATASET_DIR_PATH = ""
DEFAULT_GANN_DIR_PATH = ""

K_MEANS_CLUSTER_TOTAL_TEXT_WIDTH = 2
K_MEANS_CLUSTER_TOTAL_TEXT_FORMAT = "{:.0f}"
K_MEANS_CLUSTER_TOTAL_DEFAULT = 8
K_MEANS_CLUSTER_TOTAL_MIN = 5
K_MEANS_CLUSTER_TOTAL_MAX = 16
K_MEANS_CLUSTER_TOTAL_STEP = 1

TRAINING_RATIO_TEXT_WIDTH = 5
TRAINING_RATIO_TEXT_FORMAT = "{:.2f}"
TRAINING_RATIO_DEFAULT = 0.8
TRAINING_RATIO_MIN = 0.01
TRAINING_RATIO_MAX = 0.99
TRAINING_RATIO_STEP = 0.01

TOTAL_POPULATION_TEXT_WIDTH = 5
TOTAL_POPULATION_TEXT_FORMAT = "{:.0f}"
TOTAL_POPULATION_DEFAULT = 1000
TOTAL_POPULATION_MIN = 100
TOTAL_POPULATION_MAX = 5000
TOTAL_POPULATION_STEP = 10

MUTATION_RATE_TEXT_WIDTH = 7
MUTATION_RATE_TEXT_FORMAT = "{:.5f}"
MUTATION_RATE_DEFAULT = 0.01
MUTATION_RATE_MIN = 0.00001
MUTATION_RATE_MAX = 0.01
MUTATION_RATE_STEP = 0.00001

IMAGE_FILE_TYPES = (
    ('Image files', '*.png *.jpg *.jpeg *.bmp *.tiff *.webm *.gif'),
    ('All files', '*.*')
)
DATASET_FILE_TYPES = (
    ('CSV files', '*.csv'),
    ('All files', '*.*')
)
GANN_FILE_TYPES = (
    ('GANN files', '*.gann'),
    ('All files', '*.*')
)

ABOUT_TITLE = "Biodata Pengembang"

ABOUT_NAME = "Jason Alexander"
ABOUT_NIM = "32180082"
ABOUT_CLASS = "TIA05 - 7PTI"
ABOUT_LECTURER = "Teady Matius Surya Mulyana, S.Kom., M.Kom."

LINK_DISCORD = "https://discordapp.com/users/4106"
LINK_GITHUB = "https://github.com/FXLJA"
LINK_LINKEDIN = "https://www.linkedin.com/in/fxlja/"
LINK_STEAM = "https://steamcommunity.com/id/fxlja1411/"

PROFILE_PICTURE_WIDTH = 300
PROFILE_PICTURE_HEIGHT = 300

PROJECT_PATH = "C:/Users/Jason Alexander/Documents/GitHub/togi/"

PROFILE_PICTURE_PATH = PROJECT_PATH + "app/asset/32180082.jpg"
DISCORD_PICTURE_PATH = PROJECT_PATH + "app/asset/discord.png"
GITHUB_PICTURE_PATH = PROJECT_PATH + "app/asset/github.png"
LINKEDIN_PICTURE_PATH = PROJECT_PATH + "app/asset/linkedin.png"
STEAM_PICTURE_PATH = PROJECT_PATH + "app/asset/steam.png"
